services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - node_test_models:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: "redis:alpine"
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

volumes:
  node_test_models:
